### ISSUE TITLE
Submodules Under `louis.db` Not Installing via pip from louis-db

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/ailab-db#44]
The submodules under `louis.db`, such as `louis.db.crawler`, are missing after installation using pip. The `pyproject.toml` configuration may not be correctly specifying the inclusion of subpackages.

### Current Tree After Installation
louis/
├── db/
│   └── __init__.py
└── models/
    └── openai.py

### Steps to Reproduce
1. In a new virtual environment, execute `pip install --no-cache-dir git+https://github.com/ai-cfia/louis-db@main`.
2. Attempt `from louis.db import crawler`.
3. ImportError occurs.

### Potential Cause
Review the `pyproject.toml` configuration specifically under `[tool.setuptools]` to ensure all necessary subpackages are included.

The section may need to use the `find:` directive to automatically discover all packages and subpackages, or to list each submodule explicitly.

### Expected Behavior
All submodules under `louis.db`, including `louis.db.crawler`, should be installed and importable.

### Additional Context
If the `pyproject.toml` is updated to correctly include submodules and the issue persists, further investigation will be required.

**Comment by rngadam** [comment]
note that the plan for @JolanThomassin is to rename louis.db to ailab.db (and louis-db to ailab-db) to take into account that we want this to support multiple repos.

perhaps to not break everything at the same time, we should clone this repo to ailab-db and do the rename there. once the migration is completed, we can archive louis-db.
