### ISSUE TITLE
Getting error message when trying to run dockerfile

### ISSUE THREAD

**Issue by redat97** [ai-cfia/ailab-db#65]
When trying to run the dockerfile locally, this message appears
Ensuring extensions vector and uuid-ossp exists
NOTICE:  extension "uuid-ossp" already exists, skipping
SET
NOTICE:  extension "vector" already exists, skipping
CREATE EXTENSION
CREATE EXTENSION
psql: error: /data/schema.sql: No such file or directory
error loading /data/schema.sql. already created? use environment variable LOAD_DATA_ONLY

Seems like schema.sql is not being copied

**Comment by rngadam** [comment]
Your issue does not provide enough information on how you ran the command to get where you're at.

After some digging around:

The Dockerfile is designed to be built by:

https://github.com/ai-cfia/ailab-db/blob/main/bin/build-dataloader.sh

and run with the help of these scripts in bin/ such as:

https://github.com/ai-cfia/ailab-db/blob/main/bin/load-data-container.sh

where a volume containing the schema and data dump is provided to mount on /data; volume created from:

https://github.com/ai-cfia/ailab-db/blob/main/bin/build-data-volume.sh

Probably this could be made clearer by moving the Dockerfile to bin/ and adding a comment at the top of the Dockerfile.

Should also make sure that we have a test making sure this flows work on a sample schema.sql and small dataset within the continuous build.

**Comment by redat97** [comment]
> Your issue description does not provide enough information on how you ran the command to get where you're at (and context for what you are trying to do).
> 
> 
> 
> After some digging around:
> 
> 
> 
> The Dockerfile is designed to be built by:
> 
> 
> 
> https://github.com/ai-cfia/ailab-db/blob/main/bin/build-dataloader.sh
> 
> 
> 
> and run with the help of these scripts in bin/ such as:
> 
> 
> 
> https://github.com/ai-cfia/ailab-db/blob/main/bin/load-data-container.sh
> 
> 
> 
> where a volume containing the schema and data dump is provided to mount on /data; volume created from:
> 
> 
> 
> https://github.com/ai-cfia/ailab-db/blob/main/bin/build-data-volume.sh
> 
> 
> 
> Probably this could be made clearer by moving the Dockerfile to bin/ and adding a comment at the top of the Dockerfile.
> 
> 
> 
> Should also make sure that we have a test making sure this flows work on a sample schema.sql and small dataset within the continuous build.
> 
> 

can you tell me exactly what you want me to add to descriptions for future ones? All I did was take the dockerfile and try to run it on my machine locally how else would you have explained it?

**Comment by rngadam** [comment]
> can you tell me exactly what you want me to add to descriptions for future ones? All I did was take the dockerfile and try to run it on my machine locally how else would you have explained it?

what command-line did you use?

**Comment by redat97** [comment]
I am not sure if you are asking me a question or you are telling me what I am missing in my description
If this is a question, the answer is default vs code terminal

**Comment by rngadam** [comment]
following up in issue #66  with Melanie.

**Comment by redat97** [comment]
I'm still not sure I understand the core of the criticism and how/what I should have described it. I can't make better description if I don't know where I am going wrong
