### ISSUE TITLE
Trusted User data upload

### ISSUE THREAD

**Issue by FrancoisWerbrouck-CFIA** [ai-cfia/ailab-db#76]
We want to create a new process which will enable our test user to directly upload their data to their blob storage and the Database.

- [ ] Create process doc
- [ ] Create process template
- [ ] Linking test users to their containers
- [ ] Populating user metadata files
- [ ] Uploading files to Blob storage
- [ ] Uploading metadata to DB

**Comment by rngadam** [comment]
This issue does not have a Project assigned.

@FrancoisWerbrouck-CFIA why did you add and then remove from database?

**Comment by FrancoisWerbrouck-CFIA** [comment]
> This issue does not have a Project assigned.
> 
> @FrancoisWerbrouck-CFIA why did you add and then remove from database?

This issue was created by accident as a duplicate. I will then close it.

Here's the actual issue: #75
