### ISSUE TITLE
Testing current Score in our Schema

### ISSUE THREAD

**Issue by JolanThomassin** [ai-cfia/ailab-db#79]
# Test our schema scoring to see if they are here/accurate.
Schema tested: Louis_v005

- [ ] Pick a list of random chunk/crawl

### Test our [score weights](https://github.com/ai-cfia/ailab-db/blob/main/search-scores-and-weights.md)
- [ ] Similarity
- [ ] Recency
- [ ] Traffic
- [ ] Current 
- [ ] Typicality  

### Evaluation Criteria
**Similarity**: ?
**Recency:** Compare dates and scores to ensure alignment.
**Traffic:** ?
**Current:** Confirm that archived documents receive a score of 0.
**Typicality:** Compare the average number of site references within the dataset and verify if documents with more references receive higher scores.

**Comment by JolanThomassin** [comment]
For now, when I check Similarity and Traffic, I'm having trouble understanding how they have been implemented in the schema and, therefore, how to evaluate them. Do you have a solution, @rngadam?

> [Similarity](https://github.com/ai-cfia/ailab-db/blob/main/sql/2023-07-19-modify-score_type-add-similarity.sql): Represents the primary signal in our scoring mechanism. It denotes the measurement of how closely a document aligns with the user's query, reflecting the relevance of the document to the search criteria. It is not a static precomputed score but a dynamic metric that is computed on the fly from the search results. This ensures that the relevance is tied to the specific query, going beyond simple keyword matching. Documents with higher similarity scores are considered more relevant. By prioritizing similarity as the first signal in our scoring process, we aim to deliver search results that are more accurate.  

> [Traffic](https://github.com/ai-cfia/ailab-db/blob/main/sql/compute-traffic-score.sql): The frequency with which users consult a document influences its score. Popular or frequently accessed documents are given higher scores with the help of web traffic logs, indicating their relevance and importance to users. Warning: The home page is rated really high since it's where every user land at first.

**Comment by rngadam** [comment]
Similarity is dynamic, it cannot by definition be precomputed. we the ```1 - cosine distance``` between chunk vector and query vector for this:

https://github.com/ai-cfia/ailab-db/blob/ce18b090a17f793281248f3dd2936683eb7ba6a3/sql/2024-03-20-weighted-search-updated.sql#L75

Traffic comes from the webserver logs. I'm imported and computed a score per page in the past already:

https://github.com/ai-cfia/ailab-db/blob/main/sql/compute-traffic-score.sql

**Comment by JolanThomassin** [comment]
After testing the score seems to be accurate.
