### ISSUE TITLE
Developing a Search Function Test Utilizing LLM

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/ailab-db#9]
# Content Analysis and Scoring System for QA Using OpenAI and Azure

## Issue Description:

We aim to create a comprehensive system that extracts URLs from a web page chunk, leverages the OpenAI API through Azure to generate relevant questions and answers, and subsequently employs our search function to score the accuracy of the first ten search results in relation to the generated questions and answers.

The generated questions and answers provide a benchmark for the quality of the content analysis. When we use our search function to retrieve information related to these questions, we can assess the accuracy of the search results. This quality assurance step is crucial for ensuring the reliability of the information we collect.

![SearchEngineTesting](https://github.com/ai-cfia/louis-db/assets/98430140/165ca204-46f6-464c-9bad-9040b834350f)

https://gist.github.com/JolanThomassin/1cba745ddb3aae7f433dfb4d85298fd9

## Steps to Implement:

1. **URL Extraction:** Extract chunk using query on the database.

2. **Question-Answer Generation:** Leverage the Azure OpenAI API to generate questions and corresponding answers based on the content. Store this question-answer pairs along with their associated URLs for future reference.

3. **Retrieve the Initial Results:** Use the generated questions to perform a search on a specific subject. Retrieve the first search results from the search engine.

4. **Results Evaluation:** Assess the accuracy of the search results by comparing them to the URLs collected during the initial URL extraction process. If the URLs match, it signifies an accurate search. If there is a mismatch, adjustments to weighting parameters may be required to improve search accuracy.

- [ ] **Chunk Extraction:** Implement a method to extract chunks of text from the collected data.
- [ ] **Generated Q&A:** Create a dataset of Q&A pairs from the conversational agent's responses.
- [ ] **Retrieve Search:** Implement a search function that can retrieve the source of Q&A pairs.
- [ ] **Score Search:** Develop a scoring mechanism to evaluate the accuracy of the search results.

**Comment by rngadam** [comment]
This was written by ChatGPT right? It doesn't really reflect what we spoke about. I'd like to see a diagram to synthesize what I drew up on the board.

> Develop a web scraping script to extract random URLs from a given web page chunk. 

* we've already scrapped the data into the database
* you only need a single SQL query to fetch N random chunks and their URL

> The generated questions and answers provide a benchmark for the quality of the content analysis. 

for the quality of the search results

> Store this question-answer pairs along with their associated URL

I find the language inaccurate because of the pluralization. 

"Store each question-answer pair along with the URL of the page where the chunk comes from".

> The accuracy of the first ten search results

I didn't want us to have be stuck on ten. should be N. and scoring of the result is based on `(N-ACTUAL_URL_RANK)/N`. so if it's the 3rd result out of N=10, score is 10-3/10=0.7

There's multiple uses for this that should be enumerated:

* Compare Q&A with answers from a conversational agent
* Get set of Q/A that we can have verified with a human specialist
* Test that search for Q gives us the source for the Q&A

**Comment by rngadam** [comment]
Also record the output of the searches to finesse-data to allow @CFIALeronB to use it in his frontend as simulated data.

**Comment by JolanThomassin** [comment]
Hi @rngadam, the text was only corrected by ChatGPT to remove grammatical mistakes but I wrote it. I will do a diagram to be sure we understand the same things. I'll add the missing parts, but I'm still not sure to understand the use of the answer if you can help me on this.

**Comment by CFIALeronB** [comment]
Hi @JolanThomassin, at the request of Ricky, I am reaching out to share with you a structured example of how query JSON data is formatted for Finesse Frontend. You can access the example through the following link:
[Example Query Data](https://github.com/ai-cfia/finesse-data/blob/main/How%20do%20I%20use%20digital%20certificates.json)

Additionally, I have included a screenshot for your convenience:
![Screenshot](https://github.com/ai-cfia/louis-db/assets/133677161/de0bf225-756d-4f68-9787-8f0230dd4c9d)

In the screenshot, you’ll notice the JSON body’s structure, which prominently features an array composed of multiple JSON objects. These objects represent the search results for a particular query. The query in question corresponds directly to the title/name of the JSON file. As an example, if a user were to search for “How do I use digital certificates”, the frontend would initiate an API call, resulting in the return of the ‘How do I use digital certificates.json’ file.

Please feel free to reach out if you have any questions or need further clarification.

**Comment by JolanThomassin** [comment]
@CFIALeronB thank you very much, it seem very clear, I'll see what I can do with it and come back to you if I have difficulty 👍

**Comment by rngadam** [comment]
Thanks! stick the websequence source in a gist.GitHub.com and link from here instead of listing it here.

Suggest you update the description directly.

**Comment by JolanThomassin** [comment]
I have made some modifications to the issue description

**Comment by rngadam** [comment]
@JolanThomassin 

> Thanks! stick the websequence source in a gist.GitHub.com and link from here instead of listing it here.

I don't see this addressed @JolanThomassin

**Comment by JolanThomassin** [comment]
Indeed, I forget to add the link @rngadam, should be done now.
